### ISSUE TITLE
docsy-example fails to run locally

### ISSUE THREAD

**Issue by gauravgahlot** [google/docsy-example#100]
I created a new repo([gauravgahlot/dummy][1]) using the [Docsy Example Project][2] as a template.

Executed the following commands as suggested in steps:
```
git clone --recurse-submodules --depth 1 https://github.com/gauravgahlot/dummy.git
npm install
```

When I try to run the site locally, I get the following error:
```
 ~/dummy (master) ✔ 
➜ hugo server -vvv
INFO 2021/01/21 21:07:55 Using config file: 
Building sites … INFO 2021/01/21 21:07:55 syncing static files to /
Built in 288 ms
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): resource "scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68" not found in file cache
```

[1]: https://github.com/gauravgahlot/dummy
[2]: https://github.com/google/docsy-example#using-the-docsy-example-project-as-a-template

**Comment by gauravgahlot** [comment]
Found a similar issue here: https://github.com/google/docsy/issues/242

**Comment by LisaFC** [comment]
Hopefully we can help! 

Can you check:
- If you have an **extended** version of Hugo installed locally
- If you have installed `postcss-cli` locally

See https://www.docsy.dev/docs/getting-started/

**Comment by LisaFC** [comment]
README now updated (and docs updated to mention using Hugo as an npm module).
