### ISSUE TITLE
How to add featured background image

### ISSUE THREAD

**Issue by ajeetraina** [google/docsy-example#104]
Under https://github.com/google/docsy-example/blob/master/content/en/_index.html , I am unable to see any reference to how featured background image is being used.

**Comment by LisaFC** [comment]
Hi - here's how to change the featured background image:
https://www.docsy.dev/docs/adding-content/iconsimages/#landing-pages

You just need to put your choice of image with "background" in the file name (eg featured-background.jpg) in the same directory as the index page.

**Comment by ajeetraina** [comment]
Does that mean I don't need to specify the filename? @LisaFC

**Comment by LisaFC** [comment]
No you don't! Just called it something with "background" in the file name and put it in the same directory and Hugo will pick it up automatically.

**Comment by LisaFC** [comment]
No you don't! Just called it something with "background" in the file name and put it in the same directory and Hugo will pick it up automatically.
