### ISSUE TITLE
Integration with Feedly

### ISSUE THREAD

**Issue by ajeetraina** [google/docsy-example#108]
Does Docsy support integration with Feedly?

**Comment by LisaFC** [comment]
Yes, there's an RSS feed generated for the blog section by default, and you can configure it to add more sections if you like:
https://www.docsy.dev/docs/adding-content/content/#rss-feeds

**Comment by ajeetraina** [comment]
I am aware of RSS Feed but how can we add "feedly.com" keyword-filtered posts. @LisaFC

**Comment by LisaFC** [comment]
We haven't included anything specific for Feedly in our theme, this might be a question for the Hugo discussion forum - it's more of a generic Hugo question, and there are a lot of power Hugo users there.

Here's the general Hugo RSS info: https://gohugo.io/templates/rss/
And here's the forum. https://discourse.gohugo.io/

**Comment by ajeetraina** [comment]
Thanks @LisaFC
