### ISSUE TITLE
docsy running locally fails

### ISSUE THREAD

**Issue by huehnerlady** [google/docsy-example#127]
Hi,

I m trying to create a new website using this template.
But when I try to run the site locally with `hugo server` I get the error:

```
Error: from config: failed to resolve output format "print" from site config
```

I double checked and when I do `hugo version` I get:
```
hugo v0.83.1+extended darwin/amd64 BuildDate=unknown
```

So I do use the extended version.

Any idea what I am doing wrong?

**Comment by lamafab** [comment]
Can you tell me how you solved this?

**Comment by lamafab** [comment]
I guess this is a workaround (remove the `"print"` from the config):

```toml
[outputs]
section = ["HTML", "RSS"]
```
