### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by chalin** [google/docsy-example#151]
Related: https://github.com/google/docsy/issues/765

- [x] Rename `master` branch to `main`
- [x] Set `github_branch` to `main` in the config file. Eventually, once we've updated beyond 0.6.0, we can comment out the option since `main` will be the default - #213
- [x] Set **Production branch** to `main` via https://app.netlify.com/sites/goldydocs/settings/deploys

---

### GitHub's advice

<img width="379" alt="image" src="https://github.com/google/docsy-example/assets/4140793/aa33e365-e3dd-41a5-aeb8-ec5485938d69">

```sh
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

Adapt these instructions, depending on the name of your remote, etc.

**Comment by LisaFC** [comment]
Given that we've updated the main Docsy site, we should probably do this one as well ASAP. @chalin did you make the update on Docsy and will it be simple enough to do it again here?

**Comment by chalin** [comment]
I'd be glad to do it here. Do you want this done before or after Hugo-module support lands?

**Comment by chalin** [comment]
Done!
