### ISSUE TITLE
Update Netlify build command

### ISSUE THREAD

**Issue by chalin** [google/docsy-example#167]
For context, see https://github.com/google/docsy-example/pull/156#issuecomment-1087380189:

> Studying the deploy log I realized, that git submodules still get checked out. This doesn't do any harm, but it is not necessary either. Maybe this can be corrected? If so, I think we should open a separate ticket for this.

From https://github.com/google/docsy-example/pull/156#issuecomment-1087417447:

> OK, so the build instruction on Netlify is currently:
> 
> `cd themes/docsy && git submodule update -f --init && cd ../.. && hugo`
> 
> So will automatically check out the submodules. With Hugo Modules will it just work by running `hugo`?

/cc @deining @LisaFC

**Comment by deining** [comment]
> Can you look into it? Thanks.

This issue can be closed via #169.
