### ISSUE TITLE
hugo server step fails with error

### ISSUE THREAD

**Issue by mithuns** [google/docsy-example#19]
I just followed all the steps given in README.md.

```
git clone --recurse-submodules --depth 1 https://github.com/google/docsy-example.git
cd docsy-example
hugo server
```

But doing this ```hugo server``` fails.

below is the message I get. I didnt modify any scss files , neither do I intend to.
This is a windows 10 laptop (if that helps or matters)

![image](https://user-images.githubusercontent.com/3937267/55363910-57727780-54a4-11e9-892d-bb33b44a5eb9.png)

Has someone else faced this before me ?

**Comment by LisaFC** [comment]
Hi there,

I'm going to update the README instructions, you actually need SCSS installed to build the site, not just edit files. If you do the following:

sudo npm install -g postcss-cli
sudo npm install -g autoprefixer

you should be able to build and serve the site.

**Comment by mithuns** [comment]
Thank you
