### ISSUE TITLE
Netlify: switch to supported build image

### ISSUE THREAD

**Issue by deining** [google/docsy-example#195]
Due to the fact that Netlify fully removed support for the Ubuntu 16.04 (Xenial) build image on November 15th, 2022, the netlify build for any recent pull request fails with this error message:

```
8:05:53 PM: Build ready to start
8:05:53 PM: ---------------------------------------------------------------------
  UNSUPPORTED BUILD IMAGE

  The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.

  To enable builds for this site, select a later build image at the following link:
  https://app.netlify.com/sites/docsy-example/settings/deploys#build-image-selection

  For more details, visit the build migration guide:
  https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239
  ---------------------------------------------------------------------
```
The build image in Netlify should be updated as described [here](https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239#how-do-i-update-my-build-image-5).

**Comment by emckean** [comment]
Is this still an issue? I see Ubuntu 20 in the settings now.

**Comment by deining** [comment]
> Is this still an issue? I see Ubuntu 20 in the settings now.

Yes it is. As an example see my PR #194. I just force pushed the branch corresponding to this PR which triggered redeployment on Netlify. The build still fails, as you can see in the [deploy details](https://app.netlify.com/sites/docsy-example/deploys/63b5d2df591a85000813d877). Thanks for looking into that, I don't have privileges here.

**Comment by emckean** [comment]
Looks like I don't have privileges here either :(

**Comment by deining** [comment]
> Looks like I don't have privileges here either :(

@emckean: any idea who has privileges here?

**Comment by emckean** [comment]
probably @LisaFC?

**Comment by LisaFC** [comment]
Ok this is weird, this is a really, really old deploy that's coming from the same repo, and *I* don't have power over it.
@chenopis @RichieEscarez do either of you have access?

The "real" Docsy Example is this:
https://app.netlify.com/sites/goldydocs/overview

Did we run into this before, Erin?

**Comment by RichieEscarez** [comment]
Sorry, I don't think I ever had access to Netlify.

**Comment by LisaFC** [comment]
@chenopis can delete it!

**Comment by deining** [comment]
> @chenopis can delete it!

Great, thanks a lot!
Netlify builds correctly again, therefore closing this ticket.
