### ISSUE TITLE
Deploy Kubeflow with Password, Ingress and TLS

### ISSUE THREAD

**Issue by tshaiman** [google/docsy-example#201]
the tutorial says : "Warning:For this deployment, we will be using a simple method for authenticating to Kubeflow. For more advanced usecases, please configure your deployment to use Azure AD."

but there is no link / Reference on how to apply this suggestion

**Comment by deining** [comment]
This repo is about the docsy exanple site and unrelated to KubeFlow.
Closing this ticket.
