### ISSUE TITLE
Shortcode pageinfo not found

### ISSUE THREAD

**Issue by fastdevops** [google/docsy-example#25]
When run the command, it shows the error message.
docsy-example\content\en\docs\Reference\_index.md:9:1": failed to extract shortcode: template for shortcode "pageinfo" not found

Thanks!

**Comment by capsulecorplab** [comment]
For others encountering this issue, this is likely due to missing submodules from having cloned the repo without the `--recurse-submodules` flag. To fix, run:
```
git submodule update --init --recursive
```
then rerun `hugo serve`.
