### ISSUE TITLE
Highlighting config not working well

### ISSUE THREAD

**Issue by frodriguezsmartclip** [google/docsy-example#37]
Hi there,

I've noticed that "Highlighting config" doesn't work well to be able to highlight the code when we use

``` php
<? php echo "hello"; ?>
```
It does not color it well.

My config.toml:

```
# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = true
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = true
#pygmentsOptions = "linenos=inline"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"
```

I put this command in terminal to config pygments:

```
$ hugo gen chromastyles --style=tango > themes/mytheme/static/css/syntax.css
```
So, in my themes/mytheme/layouts/partials/head.html, I put this new line:

```
  <link rel="stylesheet" href="/css/syntax.css"/>
```

The "syntax.css" works fine (code 200), BUT, Highlighting not colours the code... :(

Any idea to fix this issue? or maybe, How to config a custom Highlighting & pygments with Hugo CMS and docsy theme? 😃 

Thanks!!!! Regards. 🙏

**Comment by LisaFC** [comment]
Are you using Hugo 0.6.0 or higher? The most recent versions use a different Markdown parser and, I think, the syntax highlighting has changed. @RichieEscarez, didn't you fix that in one of your sites?

**Comment by RichieEscarez** [comment]
In 0.6.0, syntax highlighting now defaults to Goldmark and those config options are different. To get it working, I basically copied the example config here: https://gohugo.io/getting-started/configuration-markup#goldmark

If you want to continue using Blackfriday (as your config.toml appears to be setup for), you must add/set "`defaultMarkdownHandler` to `blackfriday` in your top level markup config.", those instructions are also in that same page: https://gohugo.io/getting-started/configuration-markup#blackfriday

**Comment by frodriguezsmartclip** [comment]
> Are you using Hugo 0.6.0 or higher? The most recent versions use a different Markdown parser and, I think, the syntax highlighting has changed. @RichieEscarez, didn't you fix that in one of your sites?

Depends. On localhost, yes, this one version v.0.62:

```
frodriguez@FRODRIGUEZ-PC MINGW64 /c/Hugo/Sites/docs-adtopy (master)
$ hugo version
Hugo Static Site Generator v0.62.2/extended windows/amd64 BuildDate: unknown
```

BUT, I deploy later with Netlify which uses v.053 (hugo cms extended:

```
...
2:09:39 PM: Started restoring cached node modules
2:09:39 PM: Finished restoring cached node modules
2:09:41 PM: Installing Hugo 0.53
2:09:41 PM: Hugo Static Site Generator v0.53-8FC339DC2529FF77E494A1C12CD1FF9FBCB880A4/extended linux/amd64 BuildDate: 2018-12-24T08:38:38Z
2:09:41 PM: Started restoring cached go cache
2:09:41 PM: Finished restoring cached go cache
....
```

I dont know if it's possible use on Netlify a recently version of Hugo CMS ... 

 @RichieEscarez  I follow and put the same config as you said [there](https://gohugo.io/getting-started/configuration-markup#configure-markup), BUT on localhost, nothing change on Highlighting code 

![Anotación 2020-02-06 223639___jueves](https://user-images.githubusercontent.com/59822855/73980770-3a62cc80-4931-11ea-87ff-88b5484e94da.png)

Maybe @LisaFC is something related to docsy-theme CSS? Maybe is necessary to override other .css?

Thanks!!! 😃

**Comment by LisaFC** [comment]
You can definitely specify a more recent version of Hugo in your Netlify using Advanced Build Settings:
https://www.docsy.dev/docs/deployment/#deployment-with-netlify

I'll have a look at the config - @RichieEscarez, any further ideas?

**Comment by frodriguezsmartclip** [comment]
@LisaFC Hi, I've just configured a more recent version of Hugo on Netlify (Hugo 0.62.2 with Hugo extended version) + [Ubuntu Xenial 16.04 (default) inside Build image selection
](https://app.netlify.com/sites/docs-adtopy/settings/deploys#build-image-selection), works well (here is the log):


```
...
10:56:53 AM: Using PHP version 5.6
10:56:53 AM: Started restoring cached node modules
10:56:53 AM: Finished restoring cached node modules
10:56:53 AM: Installing Hugo 0.62.2
10:56:53 AM: Hugo Static Site Generator v0.62.2-83E50184/extended linux/amd64 BuildDate: 2020-01-05T18:57:23Z
10:56:53 AM: Started restoring cached go cache
10:56:53 AM: Finished restoring cached go cache
10:56:53 AM: unset GOOS;
10:56:53 AM: unset GOARCH;
...
```

Set new **config.toml** for goldmark highlighting as below:

```
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```

BUT, **Highlighting is still NOT working** 😢 

So maybe, it's related to another custom config for highlighting in more new Hugo's version with Netlify....

Any ideas to fix this?? Thanks!! 😃

**Comment by RichieEscarez** [comment]
So that sets the markdown processor, you also need to add `[highlight]` configuration: https://gohugo.io/getting-started/configuration-markup#highlight

Example: https://github.com/knative/website/blob/master/config/_default/markup.toml

I would also remove the Blackfriday config to ensure there is not any conflicts in your config: https://github.com/frodriguezsmartclip/docs-adtopy/blob/4a29f78c12488ca48789901d61a6404b81d97c28/config.toml#L36

**Comment by frodriguezsmartclip** [comment]
@RichieEscarez Ok, thanks for the tip to fix it.

BTW, **I changed the highlight config to use better** [Prism.JS](https://prismjs.com/), with have a lot of extra configuration (e.g: _Copy to Clipboard Button_).  Before, deleting everything related to `[markup.goldmark] o [highlight]` in **Hugo's config.toml.**

**Hugo + Prism.JS** works like a charm!!! 🎉 👌 

So, for me, this issue was solved!! 😄 

Thanks both for your help!!!

Have a nice day!! Regards
