### ISSUE TITLE
Pager.html not working well

### ISSUE THREAD

**Issue by frodriguezsmartclip** [google/docsy-example#40]
Hi there,

The example site, content of blog site, the button's pagination Next and Prev not working well:

[https://example.docsy.dev/blog/2018/10/06/easy-documentation-with-docsy/](https://example.docsy.dev/blog/2018/10/06/easy-documentation-with-docsy/)

![Anotación 2020-02-12 103238__12](https://user-images.githubusercontent.com/59822855/74321703-077e6580-4d83-11ea-977b-c85fa3169f0c.png)

The code of pager.html is this (located in [_themes\docsy\layouts\partials\pager.html_](https://github.com/google/docsy/blob/9ac9dbd708459428ff944ef95534054660034248/layouts/partials/pager.html)):

```
<ul class="list-unstyled d-flex justify-content-between align-items-center mb-0 pt-5">
  <li>
    <a {{if .PrevInSection}}href="{{.PrevInSection.RelPermalink}}"{{end}} class="btn btn-primary {{if not .PrevInSection}} disabled{{end}}"><span class="mr-1">←</span> {{ T "ui_pager_prev" }}</a>
  </li>
    <a {{if .NextInSection}}href="{{.NextInSection.RelPermalink}}"{{end}} class="btn btn-primary {{if not .NextInSection}} disabled{{end}}">{{ T "ui_pager_next" }} <span class="ml-1">→</span></a>
  </li>
</ul>
```

**The order is changed**. I don't know if it's because of the weight, or why not ... But I think it may be due to the [order-content that Hugo has set by default](https://gohugo.io/templates/lists/#order-content)...

In every filename.md the[ weigth order first (hugo docs)](https://gohugo.io/templates/lists/#by-weight) is:

> Lower weight gets higher precedence. So content with lower weight will come first.

I have all these content-files ordered ascending by weight... but the prev/next change the order....

The same thing happens with the docs section, if you put the page...

Any ideas to fix it? Thank you! 😃

**Comment by frodriguezsmartclip** [comment]
Meanwhile, changing order fix this issue for me:

```
<ul class="list-unstyled d-flex justify-content-between align-items-center mb-0 pt-5">
  <li>
    <a {{if .NextInSection}}href="{{.NextInSection.Permalink}}"{{end}} class="btn {{if .NextInSection}} btn-primary{{end}} {{if not .NextInSection}} btn-dark disabled{{end}}"><span class="mr-1">←</span> {{ T "ui_pager_prev" }}</a>        
  </li>
    <a {{if .PrevInSection}}href="{{.PrevInSection.Permalink}}"{{end}} class="btn {{if .PrevInSection}} btn-primary{{end}} {{if not .PrevInSection}} btn-dark disabled{{end}}">{{ T "ui_pager_next" }} <span class="ml-1">→</span></a>
  </li>
</ul>
```

It would be nice, have a next/prev button for going to the next section, not inside the section...  Navigate through everything docs section (for example)

If you accept my answer, we can close this issue.

Have a nice day!! 😄

**Comment by LisaFC** [comment]
Thanks for the feedback! So in our example site, the blog is **ordered by date of publication**. The  previous button brings you to the previously published post - the post you gave the screenshot of (Announcing Docsy) doesn't have a "next" post as it's the most recent post in that section.

Obviously if you want to order it differently you can override the partial, as you did!

A next/previous button for the docs section (or a next section button) would probably be simple enough to implement if enough people wanted it - feel free to create an issue in the theme repo if you're interested. https://github.com/google/docsy/issues/
