### ISSUE TITLE
Failed to extract shortcode: template for shortcode "blocks/cover" not found

### ISSUE THREAD

**Issue by willwade** [google/docsy-example#41]
`Error: Error building site: " /content/no/_index.html:7:1": failed to extract shortcode: template for shortcode "blocks/cover" not found`

I'm sure this is something simple - but found this when following the instructions..

**Comment by willwade** [comment]
im being an idiot - I didnt do a subclone..

**Comment by khareyash05** [comment]
Hey @willwade Could you pls help me with this I am getting the same error

**Comment by prabhatsharma** [comment]
@khareyash05 Below command should help you.

```shell
git clone https://github.com/google/docsy-example docsy --recursive
cd docsy
hugo serve
```

**Comment by chalin** [comment]
It works fine for me. After doing a `cd` into the repo, make sure that you first run `npm install`.

**Comment by afandian** [comment]
I got my site working fine for a few days and then it started doing this to me too. I spent a long time chasing my tail before realising that somehow my `hugo` binary had switched to a non-extended build. Maybe homebrew updated it, I'm not sure. I certainly did have the extended version running before.

But if you hit this, check your hugo version again.

**Comment by afandian** [comment]
I'm seeing this. I got my site configured, up and running a few days ago and then it stopped working a few days later. Like this ticket, I see:

```
hugo v0.103.1-b665f1e8f16bf043b9d3c087a60866159d71b48d+extended darwin/arm64 BuildDate=2022-09-18T13:19:01Z VendorInfo=gohugoio
Error: Error building site: "path_to_repo/content/_index.html:7:1": failed to extract shortcode: template for shortcode "blocks/cover" not found
```

And like https://github.com/google/docsy/issues/805 I got an error about `print` format being unrecognised, which I 'fixed' by removing that from the toml file. I tried removing the temp dir per that ticket, no dice. 

Here's another example https://github.com/google/docsy/discussions/986 but `hugo mod clean --all` doesn't fix it for me.

This feels like it's an intermittent problem, though I have no idea what the cause is.

**Comment by scottcwilson** [comment]
I also got the `Failed to extract shortcode` issue, but `hugo mod clean --all` did fix it for me.

**Comment by UedaTakeyuki** [comment]
> @khareyash05 Below command should help you.
> 
> ```shell
> git clone https://github.com/google/docsy-example docsy --recursive
> cd docsy
> hugo serve
> ```

Hello, I'm new to docsy and the issue is not fixed with ``--recursive`` as follows:

```
MacBook-Air-Early-2015:MyHugo takeyuki$ git clone https://github.com/google/docsy-example docsy --recursive
Cloning into 'docsy'...
remote: Enumerating objects: 1565, done.
remote: Counting objects: 100% (150/150), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 1565 (delta 60), reused 118 (delta 46), pack-reused 1415
Receiving objects: 100% (1565/1565), 2.61 MiB | 5.48 MiB/s, done.
Resolving deltas: 100% (762/762), done.
MacBook-Air-Early-2015:MyHugo takeyuki$ cd docsy
MacBook-Air-Early-2015:docsy takeyuki$ hugo serve
Built in 50 ms
Error: Error building site: "/Volumes/devtmp/MyHugo/docsy/content/en/_index.md:5:1": failed to extract shortcode: template for shortcode "blocks/cover" not found
```

Thank you for your suggestion.

**Comment by deining** [comment]
> Hello, I'm new to docsy and the issue is not fixed with `--recursive` as follows:
> 
> ```
> MacBook-Air-Early-2015:MyHugo takeyuki$ git clone https://github.com/google/docsy-example docsy --recursive
> Cloning into 'docsy'...
> remote: Enumerating objects: 1565, done.
> remote: Counting objects: 100% (150/150), done.
> remote: Compressing objects: 100% (92/92), done.
> remote: Total 1565 (delta 60), reused 118 (delta 46), pack-reused 1415
> Receiving objects: 100% (1565/1565), 2.61 MiB | 5.48 MiB/s, done.
> Resolving deltas: 100% (762/762), done.
> MacBook-Air-Early-2015:MyHugo takeyuki$ cd docsy
> MacBook-Air-Early-2015:docsy takeyuki$ hugo serve
> Built in 50 ms
> Error: Error building site: "/Volumes/devtmp/MyHugo/docsy/content/en/_index.md:5:1": failed to extract shortcode: template for shortcode "blocks/cover" not found
> ```
> 
> Thank you for your suggestion.

As suggested [above](https://github.com/google/docsy-example/issues/41#issuecomment-996870122):

Run `npm install` to install dependencies. Does this cure your problem?

**Comment by UedaTakeyuki** [comment]
Hi [deining](https://github.com/deining), thank you for your suggestion.
Unfortunately, the result is still the same.

```
MacBook-Air-Early-2015:docsy takeyuki$ npm install

up to date, audited 205 packages in 3s

53 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
MacBook-Air-Early-2015:docsy takeyuki$ hugo serve
Built in 40 ms
Error: Error building site: "/Volumes/devtmp/MyHugo/docsy/content/en/_index.md:5:1": failed to extract shortcode: template for shortcode "blocks/cover" not found
```

**Comment by deining** [comment]
> Hi [deining](https://github.com/deining), thank you for your suggestion. Unfortunately, the result is still the same.
> 
> ```
> MacBook-Air-Early-2015:docsy takeyuki$ npm install
> 
> up to date, audited 205 packages in 3s
> 
> 53 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> MacBook-Air-Early-2015:docsy takeyuki$ hugo serve
> Built in 40 ms
> Error: Error building site: "/Volumes/devtmp/MyHugo/docsy/content/en/_index.md:5:1": failed to extract shortcode: template for shortcode "blocks/cover" not found
> ```

What version of Hugo you are using? Your version of Hugo must be v0.110.0 or above. See the section Troubleshooting in the README.md of the project.

**Comment by UedaTakeyuki** [comment]
Thank you deining! It was 0.71.1, and running well after updated to 0.120.3.
I really appreciate your suggestons.
