### ISSUE TITLE
Update config example for Goldmark?

### ISSUE THREAD

**Issue by kmuncie** [google/docsy-example#42]
Should `config.toml` be updated to fit the latest standards of Hugo? I am thinking especially for `markup` after the change to Goldmark. Perhaps the pygments section of the config is no longer even needed?

Example of relevant Hugo documentation: https://gohugo.io/getting-started/configuration-markup#configure-markup

**Comment by LisaFC** [comment]
Yes, good suggestion, I've been meaning to do that! I updated the config so it works with Goldmark (in that everything renders, without the updates bits of the landing page went missing) but haven't addressed the markup bit. Thanks for the reminder.

**Comment by LisaFC** [comment]
Fixed (finally) in #67 along with the latest update to the template. I've left the pygments section in for users who are on an earlier Hugo version but may remove it, as it doesn't seem like we have many users pre 0.60.
