### ISSUE TITLE
build error with instructions in README.md

### ISSUE THREAD

**Issue by stuboo** [google/docsy-example#43]
Following the steps given in README.md.

```
git clone --recurse-submodules --depth 1 https://github.com/google/docsy-example.git
cd docsy-example
hugo server
```

Alas, `hugo server` fails with the following error:

```
Error: Error building site: render of "404" failed: execute of template failed: template: 
404.html:8:9: executing "404.html" at <partial "navbar.html" .>: error calling partial: 
"/Users/jrs/Sites/docsy-example/themes/docsy/layouts/partials/navbar.html:14:31": execute of 
template failed: template: partials/navbar.html:14:31: executing "partials/navbar.html" at 
<$.IsDescendant>: error calling IsDescendant: runtime error: invalid memory address or nil
 pointer dereference
```

I installed hugo from tar in the `/Sites/` directory and ran the following npm commands in the `/docsy-example/` directory.

```
sudo npm install -g postcss-cli
sudo npm install -g autoprefixer
```

Brand new to hugo (& go), so thanks in advance for the insight.

**Comment by frodriguezsmartclip** [comment]
@stuboo I followed the tutorial [using the github ui](https://www.docsy.dev/docs/getting-started/#using-the-github-ui), and no problem

Try that!

**Comment by LisaFC** [comment]
Thanks for the feedback, hope we can get you up and running! Can you check what version of Hugo you're running? Just do:
`hugo version`

**Comment by stuboo** [comment]
`Hugo Static Site Generator v0.65.2/extended darwin/amd64 BuildDate: unknown`

**Comment by gezerk** [comment]
I can confirm the same behavior. Here are my details:
```
$hugo env
Hugo Static Site Generator v0.65.1/extended darwin/amd64 BuildDate: unknown
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.13.8"
```

```
$system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.15.3 (19D76)
      Kernel Version: Darwin 19.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
```

**Comment by LisaFC** [comment]
Aha! This is a known issue in 0.65.0 and is fixed in 0.65.3. See:
https://github.com/google/docsy/issues/210

**Comment by LisaFC** [comment]
If upgrading to 0.65.3 (or the workaround suggested in the issue) works for you, we can close this.

**Comment by gezerk** [comment]
WooHooooooooo!

**Comment by gezerk** [comment]
I can now confirm that a Hugo upgrade corrects the issue. Let's close this.

```
$brew upgrade hugo
<lines omitted>
==> Upgrading 1 outdated package:
hugo 0.65.1 -> 0.65.3
```

**Comment by stuboo** [comment]
Wonderful. Thanks everyone.
