### ISSUE TITLE
package.json references non-existent tech-doc-hugo project

### ISSUE THREAD

**Issue by hartzell** [google/docsy-example#45]
This project's package.json file (and the main docsy userguide's source) seem to have been imported intact from `https://github.com/bep/tech-doc-hugo`.

I scratched my head a bit and decided that it probably didn't really matter because it's just being used as a mechanism to declare dev dependencies on postcss and autoprefixer, but wanted to confirm my understanding.

If I'm using this project as the basis for a new docs site, is there any point (or harm) in updating it?

**Comment by LisaFC** [comment]
Ahhh, that's a relic from a very very old predecessor of this project and your understanding of it is correct. I must update it myself.....
