### ISSUE TITLE
Image rendering error

### ISSUE THREAD

**Issue by kpatnayakuni** [google/docsy-example#49]
I am not able to add images to blog pages, I am getting the error below...

`Error: Error building site: "C:\Projects\GitRepos\example.com\content\en\blog\powershell\ps-int-console-on-vscode-show-on-startup.md:25:1": failed to render shortcode "imgproc": failed to process shortcode: "C:\Projects\GitRepos\example.com\layouts\shortcodes\imgproc.html:9:34": execute of template failed: template: shortcodes/imgproc.html:9:34: executing "shortcodes/imgproc.html" at <$original.Fill>: nil pointer evaluating resource.Resource.Fill`

Any help is highly appreciated. Thank you.

**Comment by hartzell** [comment]
This seems to be the same thing reported in #43, and [this comment](https://github.com/google/docsy-example/issues/43#issuecomment-591507075) links to a fix.

**Comment by LisaFC** [comment]
Let us know if that fix works for you and I can close this.

**Comment by kpatnayakuni** [comment]
Sorry for the late response, yes, that worked for me. Thank you so much for the help.
