### ISSUE TITLE
How to use github_repo in content?

### ISSUE THREAD

**Issue by razonyang** [google/docsy-example#51]
Hi, is it possible use `github_project_repo` in content?

https://github.com/google/docsy-example/blob/216831c5b5823180cf00c60e36fefb4cdffb3e91/config.toml#L102

https://github.com/google/docsy-example/blob/216831c5b5823180cf00c60e36fefb4cdffb3e91/content/en/_index.html#L12

**Comment by LisaFC** [comment]
Hi! You can't use site params directly in your Markdown text but you could create a little shortcode to use it?

So lets say you create a shortcode called repo.html and put it in your project's layouts/shortcodes directory, with this contents:

{{ .Site.Params.github_project_repo }}

And then in your page you can do:

The repo for this project is {{% repo %}}.

Hope that helps!
