### ISSUE TITLE
Alternative way to install docsy repo into themes

### ISSUE THREAD

**Issue by kaycebasques** [google/docsy-example#6]
I find git submodules to be really weird. Just a suggestion on a different way to handle the initial setup for the repo.

Ignore the themes directory in `.gitignore`:

    themes
    ...

Create a `package.json`:

```
{
  "name": "docsy-example",
  ...
  "scripts": {
    "install": "cd themes && git clone git@github.com:google/docsy.git"
  },
  ...
```

Instruct users to run `npm install` when setting up the docsy-example repo.

**Comment by LisaFC** [comment]
BTW I agree that submodules are weird but they're probably more bewildering for the theme author than the theme user, once you know that a)this is pointing to the theme repo at a specific revision and b)you can run this command to make it point to the latest version, it's pretty trivial. The main problem you can run into with this particular theme is that *it* has submodules so you need to recurse it if you want to work with it locally.

**Comment by kaycebasques** [comment]
Seems like reasonable arguments for keeping things as is. I'll close this issue.
