### ISSUE TITLE
Example website doesn't load?

### ISSUE THREAD

**Issue by hadley** [google/docsy-example#63]
https://example.docsy.dev

```
ping example.docsy.dev
ping: cannot resolve example.docsy.dev: Unknown host
```

**Comment by LisaFC** [comment]
It's up now (and hasn't been down per Netlify), may have been some transient network/DNS issue somewhere....

**Comment by hadley** [comment]
It definitely still fails for me 🤷

**Comment by LisaFC** [comment]
That is extremely weird, because I'm currently looking at it. Let me do a manual redeploy.

**Comment by LisaFC** [comment]
Just redeployed it now, it's still up. And I can ping it:

```
lcarey-macbookpro:~ lcarey$ ping example.docsy.dev
PING goldydocs.netlify.com (165.22.65.139): 56 data bytes
64 bytes from 165.22.65.139: icmp_seq=0 ttl=52 time=44.991 ms
64 bytes from 165.22.65.139: icmp_seq=1 ttl=52 time=38.159 ms
64 bytes from 165.22.65.139: icmp_seq=2 ttl=52 time=35.714 ms
64 bytes from 165.22.65.139: icmp_seq=3 ttl=52 time=38.420 ms
64 bytes from 165.22.65.139: icmp_seq=4 ttl=52 time=35.591 ms
64 bytes from 165.22.65.139: icmp_seq=5 ttl=52 time=40.964 ms
64 bytes from 165.22.65.139: icmp_seq=6 ttl=52 time=37.750 ms
64 bytes from 165.22.65.139: icmp_seq=7 ttl=52 time=40.770 ms
....
```

Are you having problems seeing any other sites?

**Comment by emckean** [comment]
I'm seeing it with no issues as well. @hadley -- is it possible you're behind any kind of content filter?

**Comment by LisaFC** [comment]
And can you see it if you go to goldydocs.netlify.com or the IP address?

**Comment by hadley** [comment]
https://goldydocs.netlify.app works just fine. The ip address loads (but reports "Not Found", presumably because there's some dynamic config happening).

dig gives:

```
; <<>> DiG 9.10.6 <<>> example.docsy.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25075
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;example.docsy.dev.             IN      A

;; ANSWER SECTION:
example.docsy.dev.      60      IN      CNAME   goldydocs.netlify.com.
goldydocs.netlify.com.  20      IN      A       192.81.212.192

;; Query time: 81 msec
;; SERVER: 192.168.154.1#53(192.168.154.1)
;; WHEN: Mon Jun 29 15:01:38 CDT 2020
;; MSG SIZE  rcvd: 97
```

**Comment by LisaFC** [comment]
Yep, that's what I'd expect (I set up the DNS record). Have you tried using another browser or trying to hit it from the command line with curl?

eg `curl https://example.docsy.dev` should get you some lovely raw HTML.

Does `nslookup` work?

I'm really not sure what's happening as I've been able to access it from a laptop and three different phones.

**Comment by hadley** [comment]
```
> nslookup https://example.docsy.dev
Server:         192.168.154.1
Address:        192.168.154.1#53

** server can't find https://example.docsy.dev: NXDOMAIN

>  curl -I https://example.docsy.dev 
curl: (6) Could not resolve host: example.docsy.dev
```

But it doesn't seem worth pursuing any further since it seems to be an issue peculiar to my computer. It's weird because I have a vanilla internet set up on my mac, and I don't have problems opening other sites. It does work on my phone, so it's not my home internet 🤷

Thanks for having a look!
