### ISSUE TITLE
Not able to run docsy example

### ISSUE THREAD

**Issue by Sakshimakkar** [google/docsy-example#80]
I performed these 3 steps
git clone --recurse-submodules --depth 1 https://github.com/google/docsy-example.git
cd docsy-example
hugo server
I am able to view website using hugo server
But when I upload the same on github, I get the following error
`Your site is having problems building: A file was included in themes/docsy/assets/vendor/bootstrap/site/docs/4.5/components/alerts.md that is a symlink or does not exist in your _includes directory. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#file-is-a-symlink.`

**Comment by tomoyanonymous** [comment]
Did you commit your built html files on your remote repo?
Github Pages does not support the build process of static site generator other than Jekyll so you need to generate html files by `hugo` command, commit generated files and push them.
https://gohugo.io/hosting-and-deployment/hosting-on-github/
Another way is to use a hosting service like Netlify. In this case, after the first integration, what you need to do when you write articles is just commit markdown files, commit them, and push them.
https://gohugo.io/hosting-and-deployment/hosting-on-netlify/

**Comment by LisaFC** [comment]
Did the previous comment resolve your issue? I'll close this if so.

**Comment by luoxinyang** [comment]
how to slove this problem?  now , I face this problem.

**Comment by luoxinyang** [comment]
Did you commit your built html files on your remote repo?
Github Pages does not support the build process of static site generator other than Jekyll so you need to generate html files by hugo command, commit generated files and push them.
https://gohugo.io/hosting-and-deployment/hosting-on-github/
Another way is using a hosting service like Netlify. In this case, after the first integration, what you need to do when you write articles is just commit markdown files, commit them, and push them.
https://gohugo.io/hosting-and-deployment/hosting-on-netlify/


this is the way slove this problem

**Comment by deining** [comment]
This issue is outdated, we now use theme component docsy as hugo module.
