### ISSUE TITLE
Make docsy-example a template repository

### ISSUE THREAD

**Issue by LisaFC** [google/docsy-example#81]
When we originally created this repo, we wanted to use the then-new template repo feature (https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-template-repository), but then discovered it didn't work with repositories that had submodules. :(

However! I just discovered that the issue I filed at the time has finally been resolved so we *could* make docsy-example into a template.

**Comment by emckean** [comment]
What if we created a new repo docsy-example-repo to test? We could direct users to it and then turn down this one if there are no issues?

**Comment by LisaFC** [comment]
It actually works fine and has literally no backward-compatibility issues so I am about to click the magic button....

**Comment by LisaFC** [comment]
Done! Let the slightly faster copying of the example commence!
