### ISSUE TITLE
Template for shortcode "blocks/cover" not found

### ISSUE THREAD

**Issue by Ronen-Sigan** [google/docsy-example#82]
_Hi,
Getting the following error when trying to run the site:_

C:\docsy-example-master> hugo server 
Start building sites … 
Built in 73 ms
Error: Error building site: "C:\Users\ronen\Documents\docsy-example-master\content\no\_index.html:7:1": failed to extract shortcode: template for shortcode "blocks/cover" not found    

_Thanks_

**Comment by LisaFC** [comment]
Can you check that you've recursed into the submodules when making your local copy? If you haven't pulled the submodules down the build won't work.

```
git submodule update --init --recursive
```

**Comment by Ronen-Sigan** [comment]
Fixed it. Thank you!

**Comment by lamafab** [comment]
> Can you check that you've recursed into the submodules when making your local copy? If you haven't pulled the submodules down the build won't work.
> 
> ```
> git submodule update --init --recursive
> ```

Ideally this should go into the README
