### ISSUE TITLE
Shallow submodules

### ISSUE THREAD

**Issue by ricovitch** [google/docsy-example#83]
Hi,

Thank you for the great work with this theme.
One thing that bother me is the size of the initial git clone for this repository.
The git clone operations just took several minutes on my machine and the result is a 380Mb folder.
Would it be possible to lower this down by using "shallow clone" for submodules ?
I think it could be configured in the .gitmodules file.
See https://stackoverflow.com/a/38895397/3641075

**Comment by deining** [comment]
The example site now uses docsy tehem component as hugo module. Git submodule was reomved, so this ticket can be closed.
