### ISSUE TITLE
fails with hugo extended

### ISSUE THREAD

**Issue by joe-getcouragenow** [google/docsy-example#89]
````
make serve 
cd /Users/apple/workspace/go/src/github.com/joe-getcouragenow/shared-doc/tools/docs/docsy-example && /Users/apple/workspace/go/src/github.com/joe-getcouragenow/shared-doc/tools/docs/hugo server
Start building sites … 

                   | EN | NO  
-------------------+----+-----
  Pages            | 47 | 76  
  Paginator pages  |  0 |  0  
  Non-page files   |  3 |  1  
  Static files     | 38 | 38  
  Processed images | 10 |  2  
  Aliases          |  4 |  0  
  Sitemaps         |  2 |  1  
  Cleaned          |  0 |  0  

Built in 3306 ms
Watching for changes in /Users/apple/workspace/go/src/github.com/joe-getcouragenow/shared-doc/tools/docs/docsy-example/{assets,content,layouts,package.json,themes}
Watching for config changes in /Users/apple/workspace/go/src/github.com/joe-getcouragenow/shared-doc/tools/docs/docsy-example/config.toml, /Users/apple/workspace/go/src/github.com/joe-getcouragenow/shared-doc/tools/docs/docsy-example/themes/docsy/config.toml
fatal error: pipe failed

goroutine 1 [running]:
runtime.throw(0x5cfc2a6, 0xb)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc003ed9860 sp=0xc003ed9830 pc=0x4038e12
runtime.sigNoteSetup(0x6e2d7e0)
        /usr/local/go/src/runtime/os_darwin.go:98 +0xc5 fp=0xc003ed9888 sp=0xc003ed9860 pc=0x4035b65
os/signal.signal_enable(0x310a56400000002)
        /usr/local/go/src/runtime/sigqueue.go:198 +0xa5 fp=0xc003ed98a8 sp=0xc003ed9888 pc=0x406d785
os/signal.enableSignal(...)
        /usr/local/go/src/os/signal/signal_unix.go:49
os/signal.Notify.func1(0x2)
        /usr/local/go/src/os/signal/signal.go:144 +0x88 fp=0xc003ed98c8 sp=0xc003ed98a8 pc=0x562b1c8
os/signal.Notify(0xc006e147e0, 0xc003ed9ae0, 0x2, 0x2)
        /usr/local/go/src/os/signal/signal.go:164 +0x162 fp=0xc003ed9940 sp=0xc003ed98c8 pc=0x562abe2
github.com/gohugoio/hugo/commands.(*commandeer).serve(0xc0006500e0, 0xc00027acc0, 0xa2, 0x100)
        /root/project/hugo/commands/server.go:498 +0x625 fp=0xc003ed9b60 sp=0xc003ed9940 pc=0x5663f05
github.com/gohugoio/hugo/commands.(*serverCmd).server(0xc00027acc0, 0xc0005c2b00, 0x6e2d1e0, 0x0, 0x0, 0x0, 0x0)
        /root/project/hugo/commands/server.go:274 +0x2b6 fp=0xc003ed9ca8 sp=0xc003ed9b60 pc=0x56626d6
github.com/gohugoio/hugo/commands.(*serverCmd).server-fm(0xc0005c2b00, 0x6e2d1e0, 0x0, 0x0, 0x0, 0x0)
        /root/project/hugo/commands/server.go:131 +0x52 fp=0xc003ed9cf0 sp=0xc003ed9ca8 pc=0x5672d92
github.com/spf13/cobra.(*Command).execute(0xc0005c2b00, 0x6e2d1e0, 0x0, 0x0, 0xc0005c2b00, 0x6e2d1e0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c fp=0xc003ed9dc0 sp=0xc003ed9cf0 pc=0x41deb1c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004ccdc0, 0xc000634290, 0x8, 0xc00011df80)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375 fp=0xc003ed9e98 sp=0xc003ed9dc0 pc=0x41df695
github.com/gohugoio/hugo/commands.Execute(0xc00019a030, 0x1, 0x1, 0x40086e5, 0xc000046178, 0x0, 0x0)
        /root/project/hugo/commands/hugo.go:90 +0xb9 fp=0xc003ed9f28 sp=0xc003ed9e98 pc=0x564f159
main.main()
        /root/project/hugo/main.go:23 +0x76 fp=0xc003ed9f88 sp=0xc003ed9f28 pc=0x56744d6
runtime.main()
        /usr/local/go/src/runtime/proc.go:204 +0x209 fp=0xc003ed9fe0 sp=0xc003ed9f88 pc=0x403b5e9
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc003ed9fe8 sp=0xc003ed9fe0 pc=0x4071521

goroutine 24 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0007f6be0)
        /go/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:154 +0x105
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:32 +0x57

goroutine 316 [select]:
github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1(0xc002290bc0, 0xc0006500e0, 0xc003fbe538, 0xc00475e270)
        /root/project/hugo/commands/hugo.go:873 +0xd9
created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
        /root/project/hugo/commands/hugo.go:871 +0x2cc

goroutine 335 [syscall]:
syscall.syscall6(0x423a960, 0x8, 0x0, 0x0, 0xc000dc8e88, 0xa, 0x6e2d4b0, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/sys_darwin.go:85 +0x2e
golang.org/x/sys/unix.kevent(0x8, 0x0, 0x0, 0xc000dc8e88, 0xa, 0x6e2d4b0, 0x0, 0x0, 0x0)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20200501145240-bc7a7d42d5c3/unix/zsyscall_darwin_amd64.go:292 +0xa6
golang.org/x/sys/unix.Kevent(0x8, 0x0, 0x0, 0x0, 0xc000dc8e88, 0xa, 0xa, 0x6e2d4b0, 0x0, 0x0, ...)
        /go/pkg/mod/golang.org/x/sys@v0.0.0-20200501145240-bc7a7d42d5c3/unix/syscall_bsd.go:413 +0x71
github.com/fsnotify/fsnotify.read(0x8, 0xc000dc8e88, 0xa, 0xa, 0x6e2d4b0, 0xc000dc8e88, 0x0, 0xa, 0x0, 0x0)
        /go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/kqueue.go:511 +0x6e
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc004a06ae0)
        /go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/kqueue.go:274 +0x831
created by github.com/fsnotify/fsnotify.NewWatcher
        /go/pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/kqueue.go:62 +0x199

goroutine 337 [select]:
github.com/gohugoio/hugo/livereload.(*hub).run(0x6dedd40)
        /root/project/hugo/livereload/hub.go:39 +0x1e9
created by github.com/gohugoio/hugo/livereload.Initialize
        /root/project/hugo/livereload/livereload.go:98 +0x45

goroutine 336 [select]:
github.com/gohugoio/hugo/watcher.(*Batcher).run(0xc002290bc0)
        /root/project/hugo/watcher/batcher.go:53 +0x174
created by github.com/gohugoio/hugo/watcher.New
        /root/project/hugo/watcher/batcher.go:42 +0x125
make: *** [serve] Error 2

````

makefile for reproduction:
```


### HUGO

HUGO_BIN=$(PWD)/hugo
HUGO_GITHUB_FILE=hugo_extended_0.79.0_macOS-64bit.tar.gz
HUGO_GITHUB_URL=https://github.com/gohugoio/hugo/releases/download/v0.79.0/$(HUGO_GITHUB_FILE)

CODE_FSPATH=$(PWD)/docsy-example

print:
	@echo HUGO_BIN: $(HUGO_BIN)
	@echo HUGO_GITHUB_FILE: $(HUGO_GITHUB_FILE)
	@echo HUGO_GITHUB_URL: $(HUGO_GITHUB_URL)
	@echo

dep-os: dep-os-delete
	# https://gohugo.io/getting-started/installing/
	#brew install hugo

	# Curl from github release
	#wget --no-check-certificate --content-disposition $(HUGO_GITHUB_URL)
	# --no-check-cerftificate was necessary for me to have wget not puke about https
	curl -LJO $(HUGO_GITHUB_URL)
	tar -xvf $(HUGO_GITHUB_FILE)
dep-os-delete:
	rm -f $(HUGO_GITHUB_FILE)
	rm -f $(HUGO_BIN)

dep-ex: dep-ex-delete
	git clone --recurse-submodules --depth 1 https://github.com/google/docsy-example.git
dep-ex-delete:
	rm -rf $(CODE_FSPATH)

serve:
	cd $(CODE_FSPATH) && $(HUGO_BIN) server




```

**Comment by LisaFC** [comment]
That's odd. Have you tried just building and serving directly rather than via a makefile, just to check that it still doesn't work?

If it's still failing, it may be a Hugo issue - I found this blog post with a workaround that might help: https://akhromieiev.com/hugo-fatal-error-pipe-failed/

**Comment by LisaFC** [comment]
Also interesting that the people with similar issues I found seemed to be also building/serving on Mac OS.

**Comment by LisaFC** [comment]
I'll see if I can find out anything else as running with watch=false does mean you need to build the site every time you make a change. :(

**Comment by LisaFC** [comment]
https://discourse.gohugo.io/t/hugo-crashing-on-hugo-server-getting-fatal-error-pipe-failed-mac/29764

**Comment by RichieEscarez** [comment]
@joe-getcouragenow would you be open to trying the workaround steps for resolving the "too many files open" error?

In Oct, I moved from a 2015 Macbook to a newer 2019 version and remember hitting that same `pipe error` when setting up my new machine. I don't think I did more than running the following commands to get past that error (which ive opened a PR for here https://github.com/google/docsy/pull/410):

```
sudo launchctl limit maxfiles 65535 200000
ulimit -n 65535
sudo sysctl -w kern.maxfiles=100000
sudo sysctl -w kern.maxfilesperproc=65535
```

More context here: https://github.com/knative/website/blob/master/DEVELOPMENT.md#file-descriptors-in-server-mode

If this resolves this `pipe error` for you, we can update that PR.

**Comment by joe-getcouragenow** [comment]
> @joe-getcouragenow would you be open to trying the workaround steps for resolving the "too many files open" error?
> 
> In Oct, I moved from a 2015 Macbook to a newer 2019 version and remember hitting that same `pipe error` when setting up my new machine. I don't think I did more than running the following commands to get past that error (which ive opened a PR for here [google/docsy#410](https://github.com/google/docsy/pull/410)):
> 

YES this maxfiles, fixes it on MAC :)  


> ```
> sudo launchctl limit maxfiles 65535 200000
> ulimit -n 65535
> sudo sysctl -w kern.maxfiles=100000
> sudo sysctl -w kern.maxfilesperproc=65535
> ```
> 
> More context here: https://github.com/knative/website/blob/master/DEVELOPMENT.md#file-descriptors-in-server-mode
> 
> If this resolves this `pipe error` for you, we can update that PR.

**Comment by LisaFC** [comment]
Thanks Richie!

**Comment by JaredOzzy** [comment]
> @joe-getcouragenow would you be open to trying the workaround steps for resolving the "too many files open" error?
> 
> In Oct, I moved from a 2015 Macbook to a newer 2019 version and remember hitting that same `pipe error` when setting up my new machine. I don't think I did more than running the following commands to get past that error (which ive opened a PR for here [google/docsy#410](https://github.com/google/docsy/pull/410)):
> 
> ```
> sudo launchctl limit maxfiles 65535 200000
> ulimit -n 65535
> sudo sysctl -w kern.maxfiles=100000
> sudo sysctl -w kern.maxfilesperproc=65535
> ```
> 
> More context here: https://github.com/knative/website/blob/master/DEVELOPMENT.md#file-descriptors-in-server-mode
> 
> If this resolves this `pipe error` for you, we can update that PR.

These steps worked for me too!

Thanks.

**Comment by LisaFC** [comment]
Docs updated in https://github.com/google/docsy/pull/410

**Comment by LisaFC** [comment]
I'm going to close this as we have a working workaround, do reopen if it's not working for everyone.

**Comment by ascensus-mdb** [comment]
> @joe-getcouragenow would you be open to trying the workaround steps for resolving the "too many files open" error?
> 
> In Oct, I moved from a 2015 Macbook to a newer 2019 version and remember hitting that same `pipe error` when setting up my new machine. I don't think I did more than running the following commands to get past that error (which ive opened a PR for here [google/docsy#410](https://github.com/google/docsy/pull/410)):
> 
> ```
> sudo launchctl limit maxfiles 65535 200000
> ulimit -n 65535
> sudo sysctl -w kern.maxfiles=100000
> sudo sysctl -w kern.maxfilesperproc=65535
> ```
> 
> More context here: https://github.com/knative/website/blob/master/DEVELOPMENT.md#file-descriptors-in-server-mode
> 
> If this resolves this `pipe error` for you, we can update that PR.

That works for me, thanks! But it seems I have to type it every time I re-launch my computer. Is there a way to set it up pernamently?
