### ISSUE TITLE
public folder

### ISSUE THREAD

**Issue by MAlexGR** [google/docsy-example#92]
Hi everyone!

May I ask where the public directory is? In other words, I cloned the example and made it run locally but now can't deploy it to Netlify, because there is no public directory. Netlify awaits for a "publish" variable and I don't know what to provide there. I did follow your instructions how to deploy my site to Netlify, either by setting up build options on Netlify itself or by creating a netlify.toml file. Both attempts failed. Where exactly are the generated html files?

Alex

**Comment by gwatts** [comment]
Hi @MAlexGR - It should just be "public" - Here's a really simple `netlify.toml` that i use with my example template https://github.com/gwatts/mostlydocs/blob/main/netlify.toml

**Comment by MAlexGR** [comment]
Hi @gwatts! Thank you for your comment.

Sorry, I wasn't clear. I did follow the steps given [here](https://www.docsy.dev/docs/getting-started/#using-the-command-line) and created a *locally working site*. I then connected this local repo with a GitHub one. Then I tried to deploy the site throught the chain (my) PC - GitHub - Netlify, again following the steps given [here](https://www.docsy.dev/docs/deployment/#deployment-with-netlify).

From there nothing worked! Netlify was unable to create the site, giving me various errors. I tried to configure the building process either directly on Netlify or through a netlify.toml file (almost the same as the one you suggested and always according to the previous instructions). Nothing!

I remembered that Hugo creates a public folder and puts the html files it creates, in it. This folder did not exist on the example site. Also I can't find any html file at all. So, *I guess*, Netlify fails because it can't find neither a public folder nor html files. Am I right?

Does the creation process takes place at server site (Netlify) as in my laptop? To be honest, I don't understand how the "submodule" concept for Docsy works and I blindly followed the instructions. Can you give me an idea how this chain proccesses work? What sould I do (as I said, the `netlify.toml` you propose doesn't make the difference)?

Thank you.

Alex

**Comment by MAlexGR** [comment]
I solved it!

The whole thing was about the PostCSS. According to user guide's ["getting started"](https://www.docsy.dev/docs/getting-started/#install-postcss) section, I had to install PostCSS in order to "... build or update your site’s CSS resources ...". I thought I had taken the necessary steps to install it but in the end it was not so.

What is not mentioned in the above section is that the installation of postcss includes the creation of a "package.json" file, a "package-lock.json" file and a "node_modules" folder with a set of subfolders in it. All this is created automatically and all this is required by Netlify to build the site! The fun part is when I looked carefully at the log of the failed version on Netlify, I came across warnings and errors that I just remembered were similar to what I encountered when I tried to install PostCSS (about a week ago). I spotted the problem by accident!

To be brief, I would suggest you fill in the following in the user guide, in the above mentioned section:
- install NodeJS on your system
- *in the working directory*
-  : give the command `npm init`. This will create the `package.json` file.
- install `autoprefixer` with` sudo npm install -D --save autoprefixer`

What it is not mentioned there is:

- how to install `postcss` it's not obvious at all
- the procedure it's note easy (at least wasn't on my ubuntu 20)
-

**Comment by gwatts** [comment]
@MAlexGR Oh great!  So glad you got it figured out and thanks for updating the issue - That's a great observations about the docs - I think the docs assume that you're starting from this template that already includes the `package.json` file, in which case `npm install` should be all you need (though the docs don't make that clear as linked above)

The "Use the Docsy theme in your own site " doesn't mention the npm steps at all though, so i that's probably a good spot to focus on too

@LisaFC is the docs (and Docsy) guru; any thoughts?

**Comment by LisaFC** [comment]
So there's a general prereqs section at the top that does say that you need to do the npm steps for any of the usage options (and will soon also include our new exciting Docker container option for people who don't want to have to install postCSS, hugo, etc.), but yes, the Docsy theme section doesn't mention the `npm init` step - that's a really good spot! I'll try to clarify the docs a bit to make it clear which prereqs are necessary if you're using the template site versus just using the theme.
